# Book settings
title: Introduction to Topic Modeling and Text Classification
author: William Mattingly
logo: 'images/data_science_lab_logo.png'
execute:
  execute_notebooks: 'off'
parse:
  myst_extended_syntax: true

# Information about where the book exists on the web
repository:
  url: https://github.com/wjbmattingly/topic_modeling_textbook  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true

